service: serverless-boilerplate

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  timeout: 10
  memory: 512
  environment:
    SERVICE_NAME: serverless-boilerplate

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  serverless-offline:
    port: 4000
  webpackIncludeModules: true

package:
  individually: true

functions:
  echo:
    handler: src/handlers/echo/echo.default
    events:
      - http:
          path: echo
          method: any
          cors: true
