service: serverless-boilerplate

frameworkVersion: ">=1.33.2 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  timeout: 10
  memory: 512
  environment:
    SERVICE_NAME: serverless-boilerplate

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  webpack:
    includeModules: true

package:
  individually: true

functions:
  echo:
    handler: src/handlers/echo/echo.default
    events:
      - http:
          path: echo
          method: any
          cors: true
